name: check stats script
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
